# ワークフローの名前
name: Go CI

# トリガーになる Github イベント
#　今回は、リポジトリへのコミット（push）と PR 作成(pull_request)をトリガーにします
on:
  push:
  pull_request:

# ジョブ定義
jobs:
  # ジョブ名
  test:
    # ジョブ実行環境の指定
    runs-on: ubuntu-latest
    # ジョブ内で実行する step を定義
    steps:
      # リポジトリからソースコードの取得
      - uses: actions/checkout@v3
      # Go の実行環境 Set up
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.20
      # テストの実行
      - name: Run Test
        run: go test -v ./...
